generatorName: typescript
outputDir: /local/src
inputSpec: /local/openapi.clean.json
templateDir: /local/templates
gitUserId: "thinger-io"
gitRepoId: "thinger-node"
additionalProperties:
  disallowAdditionalPropertiesIfNotPresent: false
  licenseName: "MIT"
  npmName: "@thinger-io/thinger-node"
  npmVersion: "0.1.1"
  platform: "node"
  supportsES6: true
  useObjectParameters: false
  importFileExtension: ".js"
  #validationAttributes: true
  #withInterfaces: true
openapiNormalizer:
  SIMPLIFY_ONEOF_ANYOF: true
  REMOVE_X_INTERNAL: true
  KEEP_ONLY_FIRST_TAG_IN_OPERATION: true
  SIMPLIFY_ANYOF_STRING_AND_ENUM_STRING: true
  REFACTOR_ALLOF_WITH_PROPERTIES_ONLY: false
reservedWordsMappings:
  delete: remove
  export: exportData
