/**
 * Thinger.io Server API
 * Thinger.io Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

/**
* Comparison expressions for conditional evaluation
*/
export enum ComparisonExpressions {
    Above = 'above',
    Below = 'below',
    Equal = 'equal',
    NotEqual = 'not_equal',
    Inside = 'inside',
    Outside = 'outside'
}
