/**
 * Thinger.io Server API
 * Thinger.io Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DeviceUpdateCallbackRequestActions } from '../models/DeviceUpdateCallbackRequestActions.js';
import { DeviceUpdateCallbackRequestProperties } from '../models/DeviceUpdateCallbackRequestProperties.js';
import { HttpFile } from '../http/http.js';

export class DeviceUpdateCallbackRequest {
    'actions'?: DeviceUpdateCallbackRequestActions;
    'properties'?: DeviceUpdateCallbackRequestProperties;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "actions",
            "baseName": "actions",
            "type": "DeviceUpdateCallbackRequestActions",
            "format": ""
        },
        {
            "name": "properties",
            "baseName": "properties",
            "type": "DeviceUpdateCallbackRequestProperties",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeviceUpdateCallbackRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
