/**
 * Thinger.io Server API
 * Thinger.io Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DeviceUpdateRequestAssetGroup } from '../models/DeviceUpdateRequestAssetGroup.js';
import { HttpFile } from '../http/http.js';

export class DeviceUpdateRequest {
    'assetGroup'?: DeviceUpdateRequestAssetGroup;
    'assetType'?: DeviceUpdateRequestAssetGroup;
    'credentials'?: string;
    'description'?: string;
    'enabled'?: boolean;
    'name'?: string;
    'product'?: DeviceUpdateRequestAssetGroup;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "assetGroup",
            "baseName": "asset_group",
            "type": "DeviceUpdateRequestAssetGroup",
            "format": ""
        },
        {
            "name": "assetType",
            "baseName": "asset_type",
            "type": "DeviceUpdateRequestAssetGroup",
            "format": ""
        },
        {
            "name": "credentials",
            "baseName": "credentials",
            "type": "string",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "product",
            "baseName": "product",
            "type": "DeviceUpdateRequestAssetGroup",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeviceUpdateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
