/**
 * Thinger.io Server API
 * Thinger.io Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

/**
 * @type DeviceUpdateRequestAssetGroup
 * Type
 * @export
 */
export type DeviceUpdateRequestAssetGroup = string;

/**
* @type DeviceUpdateRequestAssetGroupClass
* @export
*/
export class DeviceUpdateRequestAssetGroupClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}
