/**
 * Thinger.io Server API
 * Thinger.io Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class DeviceCloneRequest {
    /**
    * A brief description of the resource, providing context or additional information, limited to 255 characters.
    */
    'description'?: string;
    /**
    * A unique identifier for resources, consisting of alphanumeric characters, underscores, or hyphens, and limited to 32 characters.
    */
    'device': string;
    'enabled'?: boolean;
    /**
    * The name of the resource, limited to 255 characters. It can include any character.
    */
    'name'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "device",
            "baseName": "device",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DeviceCloneRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
