/**
 * Thinger.io Server API
 * Thinger.io Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductConditionalIconConditionsInnerOneOf } from '../models/ProductConditionalIconConditionsInnerOneOf.js';
import { ProductConditionalIconConditionsInnerOneOf1 } from '../models/ProductConditionalIconConditionsInnerOneOf1.js';
import { HttpFile } from '../http/http.js';

/**
 * @type ProductConditionalIconConditionsInner
 * Type
 * @export
 */
export type ProductConditionalIconConditionsInner = ProductConditionalIconConditionsInnerOneOf | ProductConditionalIconConditionsInnerOneOf1;

/**
* @type ProductConditionalIconConditionsInnerClass
* @export
*/
export class ProductConditionalIconConditionsInnerClass {
    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;
}

