/**
 * Thinger.io Server API
 * Thinger.io Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

/**
* Icon schema for a product
*/
export class ProductIcon {
    'background'?: string;
    'color'?: string;
    'size'?: number;
    'source': string;
    /**
    * Icon type: font-awesome or svg
    */
    'type': ProductIconTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "background",
            "baseName": "background",
            "type": "string",
            "format": ""
        },
        {
            "name": "color",
            "baseName": "color",
            "type": "string",
            "format": ""
        },
        {
            "name": "size",
            "baseName": "size",
            "type": "number",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ProductIconTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductIcon.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum ProductIconTypeEnum {
    Fa = 'fa',
    Svg = 'svg'
}

