/**
 * Thinger.io Server API
 * Thinger.io Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductConditionalIconConditionsInner } from '../models/ProductConditionalIconConditionsInner.js';
import { ProductIcon } from '../models/ProductIcon.js';
import { HttpFile } from '../http/http.js';

/**
* Conditional Icon schema for a product
*/
export class ProductConditionalIcon {
    'conditions'?: Array<ProductConditionalIconConditionsInner>;
    'icon': ProductIcon;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "conditions",
            "baseName": "conditions",
            "type": "Array<ProductConditionalIconConditionsInner>",
            "format": ""
        },
        {
            "name": "icon",
            "baseName": "icon",
            "type": "ProductIcon",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductConditionalIcon.attributeTypeMap;
    }

    public constructor() {
    }
}
