/**
 * Thinger.io Server API
 * Thinger.io Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ComparisonExpressions } from '../models/ComparisonExpressions.js';
import { OperatorExpressions } from '../models/OperatorExpressions.js';
import { HttpFile } from '../http/http.js';

export class ProductConditionalIconConditionsInner {
    'comparison': ComparisonExpressions;
    'field': string;
    'operator': OperatorExpressions;
    'value': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "comparison",
            "baseName": "comparison",
            "type": "ComparisonExpressions",
            "format": ""
        },
        {
            "name": "field",
            "baseName": "field",
            "type": "string",
            "format": ""
        },
        {
            "name": "operator",
            "baseName": "operator",
            "type": "OperatorExpressions",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductConditionalIconConditionsInner.attributeTypeMap;
    }

    public constructor() {
    }
}


