/**
 * Thinger.io Server API
 * Thinger.io Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductConfig } from '../models/ProductConfig.js';
import { HttpFile } from '../http/http.js';

export class ProductCreateRequest {
    'config'?: ProductConfig;
    /**
    * A brief description of the resource, providing context or additional information, limited to 255 characters.
    */
    'description'?: string;
    'enabled'?: boolean;
    /**
    * The name of the resource, limited to 255 characters. It can include any character.
    */
    'name': string;
    /**
    * A unique identifier for resources, consisting of alphanumeric characters, underscores, or hyphens, and limited to 32 characters.
    */
    'product': string;
    'profile'?: any;
    'services'?: any;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "config",
            "baseName": "config",
            "type": "ProductConfig",
            "format": ""
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "enabled",
            "baseName": "enabled",
            "type": "boolean",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "product",
            "baseName": "product",
            "type": "string",
            "format": ""
        },
        {
            "name": "profile",
            "baseName": "profile",
            "type": "any",
            "format": ""
        },
        {
            "name": "services",
            "baseName": "services",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductCreateRequest.attributeTypeMap;
    }

    public constructor() {
    }
}
