/**
 * Thinger.io Server API
 * Thinger.io Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { ProductConditionalIcon } from '../models/ProductConditionalIcon.js';
import { ProductField } from '../models/ProductField.js';
import { HttpFile } from '../http/http.js';

/**
* Configuration schema for a product
*/
export class ProductConfig {
    'fields'?: Array<ProductField>;
    'icons'?: Array<ProductConditionalIcon>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fields",
            "baseName": "fields",
            "type": "Array<ProductField>",
            "format": ""
        },
        {
            "name": "icons",
            "baseName": "icons",
            "type": "Array<ProductConditionalIcon>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ProductConfig.attributeTypeMap;
    }

    public constructor() {
    }
}
