/**
 * Thinger.io Server API
 * Thinger.io Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class PropertyForm {
    'fields': any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "fields",
            "baseName": "fields",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PropertyForm.attributeTypeMap;
    }

    public constructor() {
    }
}
