/**
 * Thinger.io Server API
 * Thinger.io Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { PropertyForm } from '../models/PropertyForm.js';
import { HttpFile } from '../http/http.js';

/**
* Schema for updating a property
*/
export class PropertyUpdate {
    /**
    * A brief description of the resource, providing context or additional information, limited to 255 characters.
    */
    'description'?: string;
    'form'?: PropertyForm;
    /**
    * The name of the resource, limited to 255 characters. It can include any character.
    */
    'name'?: string;
    /**
    * A unique identifier for resources, consisting of alphanumeric characters, underscores, or hyphens, and limited to 32 characters.
    */
    'property'?: string;
    'type'?: PropertyUpdateTypeEnum;
    'value': any | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "form",
            "baseName": "form",
            "type": "PropertyForm",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "property",
            "baseName": "property",
            "type": "string",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "PropertyUpdateTypeEnum",
            "format": ""
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PropertyUpdate.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PropertyUpdateTypeEnum {
    Empty = '',
    Configuration = 'configuration'
}

