/**
 * Thinger.io Server API
 * Thinger.io Server API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http.js';

export class PropertyPerm {
    'hidden'?: Set<PropertyPermHiddenEnum>;
    'readOnly'?: Set<PropertyPermReadOnlyEnum>;

    static readonly discriminator: string | undefined = undefined;

    static readonly mapping: {[index: string]: string} | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "hidden",
            "baseName": "hidden",
            "type": "Set<PropertyPermHiddenEnum>",
            "format": ""
        },
        {
            "name": "readOnly",
            "baseName": "readOnly",
            "type": "Set<PropertyPermReadOnlyEnum>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return PropertyPerm.attributeTypeMap;
    }

    public constructor() {
    }
}

export enum PropertyPermHiddenEnum {
    Owner = 'owner',
    Member = 'member'
}
export enum PropertyPermReadOnlyEnum {
    Owner = 'owner',
    Member = 'member'
}

